[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pcs"
version = "0.0.2"
description = "PCS instalation package."
authors = [
    "PCS <https://productivecloudsolutions.com>",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
package-dir = {"" = "pcs"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false