[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pcs"
version = "0.0.2"
description = "PCS instalation package."
license = "Proprietary"
authors = [
    "PCS <https://productivecloudsolutions.com>",
]
maintainers = [
]
readme = ["README.md"]
repository = "https://github.com/Productive-Cloud-Solutions/PCS-Lambda-Framework"
packages = [
    { include = "pcs" },
]
